name: Phpstan
on: [push, pull_request]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2 # or alternative dependency management
      - uses: php-actions/phpstan@v1
